apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js
spec:
  selector:
    matchLabels:
      run: node-js
  replicas: 1
  template:
    metadata:
      labels:
        run: node-js
    spec:
      containers:
      - name: node-js
        image: kapilch/nodejs
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: node-js
  labels:
    run: node-js
spec:
  ports:
  - port: 80
  selector:
    run: node-js
